### ISSUE TITLE
Reddit complaints: icon

### ISSUE THREAD

**Issue by RoyIacob** [mcwhitak/Textalyzer#34]
"I've been using the app for a little while now, and the only major issue I have is the icon. It doesn't look great, and the circle feels to small...IMHO I think there should be more padding around the glyph."

"It just seems poor in comparison to other icons on the page too...with the exception of the crap that is subway surfers. Their icons are color rich, and in comparison yours it just didn't fit. I don't mean to be insulting at all, though so I am sorry if I sound rude."

Probably looks ugly when the other icon shows (on bigger devices?)

**Comment by mcwhitak** [comment]
Fixed the icon.
